module.exports = {
  DISCORD_TOKEN: "TU_TOKEN",
  CHANNEL_ID: "ID_CANAL",
  WEBHOOK_URL: "TU_WEBHOOK_DISCORD",

  ATERNOS_EMAIL: "TU_EMAIL",
  ATERNOS_PASSWORD: "TU_PASS",

  SERVER_IP: "TU_SERVER.aternos.me",
  CHECK_INTERVAL: 30000
};
